Repository devdreamsolution/laravel-donate-system, pull requests merged in 2021-02, with the labels that each got.

#8 Devdreamsolution
  app/Models/User.php
  composer.json
  composer.lock
  config/permission.php
  database/migrations/2021_02_01_124457_create_permission_tables.php
  database/seeders/DatabaseSeeder.php
  database/seeders/PermissionSeeder.php
  database/seeders/UserSeeder.php
Labels: enhancement

#10 Devdreamsolution
  app/Http/Controllers/Admin/UserController.php
  composer.json
  composer.lock
  resources/lang/en/global.php
  resources/views/admin/users/create.blade.php
  resources/views/admin/users/edit.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/auth/register.blade.php
  resources/views/partials/admin/javascript.blade.php
  resources/views/partials/admin/menubar.blade.php
  resources/views/partials/admin/stylesheet.blade.php
  routes/web.php
Labels: enhancement

#11 Fix fake phone and users order
  app/Http/Controllers/Admin/UserController.php
  database/seeders/UserSeeder.php
  resources/views/admin/users/index.blade.php
Labels: bug

#15 Devdreamsolution
  LICENSE
  app/Http/Controllers/Admin/UserController.php
  public/assets/countries.json
  resources/lang/en/global.php
  resources/views/admin/users/index.blade.php
  resources/views/auth/register.blade.php
Labels: bug

#16 Admin permission is necessary when user create. #14
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/global.php
  resources/views/admin/users/create.blade.php
  resources/views/admin/users/edit.blade.php
  resources/views/admin/users/index.blade.php
Labels: bug

#19 Devdreamsolution
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Kernel.php
  app/Http/Middleware/Activate.php
  database/seeders/UserSeeder.php
  resources/lang/en/global.php
  resources/lang/en/validation.php
  resources/views/auth/login.blade.php
  resources/views/auth/verify.blade.php
  routes/web.php
Labels: bug, enhancement

#24 referral team
  app/Http/Controllers/Admin/ReferalTeamController.php
  resources/views/admin/referal-teams/index.blade.php
Labels: bug

#25 Devdreamsolution
  README.md
  app/Http/Controllers/API/Auth/AuthController.php
  app/Models/User.php
  composer.json
  composer.lock
  database/factories/UserFactory.php
  database/seeders/UserSeeder.php
  screenshots/mlm.png
Labels: bug, enhancement
